/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ShareholdersRouteImport } from './routes/shareholders'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SectorsRouteImport } from './routes/sectors'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareholdersIndexRouteImport } from './routes/shareholders.index'
import { Route as ShareholdersIdRouteImport } from './routes/shareholders.$id'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareholdersRoute = ShareholdersRouteImport.update({
  id: '/shareholders',
  path: '/shareholders',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsRoute = SectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareholdersIndexRoute = ShareholdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShareholdersRoute,
} as any)
const ShareholdersIdRoute = ShareholdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShareholdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/sectors': typeof SectorsRoute
  '/services': typeof ServicesRoute
  '/shareholders': typeof ShareholdersRouteWithChildren
  '/team': typeof TeamRoute
  '/shareholders/$id': typeof ShareholdersIdRoute
  '/shareholders/': typeof ShareholdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/sectors': typeof SectorsRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/shareholders/$id': typeof ShareholdersIdRoute
  '/shareholders': typeof ShareholdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/sectors': typeof SectorsRoute
  '/services': typeof ServicesRoute
  '/shareholders': typeof ShareholdersRouteWithChildren
  '/team': typeof TeamRoute
  '/shareholders/$id': typeof ShareholdersIdRoute
  '/shareholders/': typeof ShareholdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/news'
    | '/products'
    | '/register'
    | '/sectors'
    | '/services'
    | '/shareholders'
    | '/team'
    | '/shareholders/$id'
    | '/shareholders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/news'
    | '/products'
    | '/register'
    | '/sectors'
    | '/services'
    | '/team'
    | '/shareholders/$id'
    | '/shareholders'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/news'
    | '/products'
    | '/register'
    | '/sectors'
    | '/services'
    | '/shareholders'
    | '/team'
    | '/shareholders/$id'
    | '/shareholders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  NewsRoute: typeof NewsRoute
  ProductsRoute: typeof ProductsRoute
  RegisterRoute: typeof RegisterRoute
  SectorsRoute: typeof SectorsRoute
  ServicesRoute: typeof ServicesRoute
  ShareholdersRoute: typeof ShareholdersRouteWithChildren
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shareholders': {
      id: '/shareholders'
      path: '/shareholders'
      fullPath: '/shareholders'
      preLoaderRoute: typeof ShareholdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors': {
      id: '/sectors'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shareholders/': {
      id: '/shareholders/'
      path: '/'
      fullPath: '/shareholders/'
      preLoaderRoute: typeof ShareholdersIndexRouteImport
      parentRoute: typeof ShareholdersRoute
    }
    '/shareholders/$id': {
      id: '/shareholders/$id'
      path: '/$id'
      fullPath: '/shareholders/$id'
      preLoaderRoute: typeof ShareholdersIdRouteImport
      parentRoute: typeof ShareholdersRoute
    }
  }
}

interface ShareholdersRouteChildren {
  ShareholdersIdRoute: typeof ShareholdersIdRoute
  ShareholdersIndexRoute: typeof ShareholdersIndexRoute
}

const ShareholdersRouteChildren: ShareholdersRouteChildren = {
  ShareholdersIdRoute: ShareholdersIdRoute,
  ShareholdersIndexRoute: ShareholdersIndexRoute,
}

const ShareholdersRouteWithChildren = ShareholdersRoute._addFileChildren(
  ShareholdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  NewsRoute: NewsRoute,
  ProductsRoute: ProductsRoute,
  RegisterRoute: RegisterRoute,
  SectorsRoute: SectorsRoute,
  ServicesRoute: ServicesRoute,
  ShareholdersRoute: ShareholdersRouteWithChildren,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
